Feature/specify locales in get translations method
spatie/laravel-translatable pull request #299
Opened 2021-09-27 16:42 UTC by khalilst

This PR adds a new `$locales` argument to the `getTranslations` method to filter the translations.
Exmaple:
```php
$model->name = [
    'en' => 'Hello',
    'fr' => 'Bonjour',
    'de' => 'Hallo',
];

$model->getTranslations('name', ['en', 'fr']); // returns ['en' => 'Hello', 'fr' => 'Bonjour']
```

Also, the **tests** implemented for this feature and the `README` updated.

2021-09-27 17:48 UTC, freekmurze requested changes

2021-09-27 17:48 UTC, freekmurze commented on src/HasTranslations.php
> +                fn ($value, $locale) => $value !== null && $value !== '' && ($locales === null || in_array($locale, $locales ?? [])),
To me, this is unreadable. Could you replace the conditional with a well named function that uses early returns?

2021-09-27 17:48 UTC, freekmurze commented on README.md
> +``` php
In this readme, we don't just offer the function signature, but always give a nice description and example

2021-09-28 14:20 UTC, freekmurze approved these changes

2021-09-28 14:20 UTC, merged

2021-09-28 14:20 UTC, freekmurze commented
Thanks!

2021-09-28 17:17 UTC, khalilst commented
@freekmurze My pleasure and thank you too!

2021-10-04 09:19 UTC, killgt commented on src/HasTranslations.php
> +    protected function filterTranslations(string $value = null, string $locale = null, array $allowedLocales = null): bool
We are having issues with this line, as some translation values aren't strings, 5.0.2 introduces a breaking changes.